### ISSUE TITLE
Support for SSL (https)

### ISSUE THREAD

**Issue by IknowJoseph** [hotosm/hotosm-website#14] opened 2014-10-01 06:34 UTC
Could we enable https on the site? It is unlikely that browsing the HOT website is going to be a privacy concern for many people but the user login is currently sent over plaintext (using OpenID presumably fixes this for those that have enabled it) and Google have begun to regard https as a ranking factor [0]. Site wide https by default would solve the login issue, help the Google ranking and allow us to worry less about visitor privacy in the future.

openstreetmap.org already as a https wildcard cert that could presumably be used without any particular effort for hot.openstreetmap.org, but I don't know about the hotosm.org domain (presumably many error messages would occur). 

[0] http://googlewebmastercentral.blogspot.com/2014/08/https-as-ranking-signal.html

**Comment by xamanu** [comment] 2015-05-01 05:00
@dodobas and @mikelmaron: Now that we have consolidated to one single domain: hotosm.org (#6) Can we proceed in buying this certificate?

**Comment by xamanu** [comment] 2015-06-09 19:37
I mentioned this in the TechWG meeting. @dodobas is going to talk with Tyler about this. Some cheap options for certificates are listed here: https://www.namecheap.com/security/ssl-certificates/comodo.aspx

**Comment by IknowJoseph** [comment] 2015-08-28 13:44
I've seen that https://hotosm.org exists, which is awesome, but it currently points to the piwik instance which should be only at https://piwik.hotosm.org 

Presumably the 000-default (or default-ssl) or equivalent needs updating to include an entry for https on the usual web site.

**Comment by stlejer-morvrini** [comment] 2015-10-09 08:08
I totally support Joseph's suggestion as I am experiencing a situation which requires https: TM advertised through an iframe in a https web site.
The site has become https recently, and all the visitors see now is an empty iframe and some would conclude a bit quickly that the TM itself does't work.

**Comment by dodobas** [comment] 2015-10-09 11:32
we have support for https, as you can see on piwik site, so it's not a problem to simply add https support main web site and tasking manager, however, if the site uses external resources which are not defined as *protocol agnostic* those resources will blocked by any modern browser, making site unusable.

I'm waiting for @xamanu to 'resurface' to coordinate migration to the https.

Reading previous comments seems like the issue is not WWW but TM, is that correct ?

**Comment by xamanu** [comment] 2015-10-28 21:22
I'm back @dodobas. Lets coordinate it.

**Comment by dodobas** [comment] 2015-10-29 09:31
@xamanu it has been enabled, but the site is broken because of mixed content

this is usually fixed by using PRURL (https://en.wikipedia.org/wiki/Wikipedia:Protocol-relative_URL) for resources, I don't know if you will need to fix something within drupal, but if you need anything done on the server... my username is same on Skype, twitter, IRC,.... contact me

**Comment by xamanu** [comment] 2015-10-30 20:02
@dodobas, I fixed the mixed content. But because of the server configuration simple redirects from http to https don't work. Can you please check the configuration and make such a redirect on a web server level, please. I think it is worth to figure out if we can use HTTP Strict Transport Security (https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security) on the web server configuration.

Thank you!

**Comment by xamanu** [comment] 2015-10-30 20:11
@dodobas configured the web server well with redirection and HSTS in the headers. Thank you!

**Comment by dodobas** [comment] 2015-11-05 17:00
I've noticed that on page https://hotosm.org/get-involved/disaster-mapping there is an external resource `http://static.addtoany.com/menu/page.js`

this needs to be changed to https

**Comment by xamanu** [comment] 2016-04-20 02:00
Done. Closing here.

**Closed by xamanu** 2016-04-20 02:00 UTC
Labels: enhancement, infrastructure
