### ISSUE TITLE
Title backdrop image only showing for first news item on homepage

### ISSUE THREAD

**Issue by cgiovando** [hotosm/hotosm-website#112] opened 2016-07-27 16:30 UTC
In the "Latest News section of the homepage, only the most recent item shows the backdrop image. See screenshot below:

<img width="705" alt="screen shot 2016-07-27 at 09 28 23" src="https://cloud.githubusercontent.com/assets/10201533/17183486/96425ad2-53dc-11e6-8819-7371442e3b87.png">

**Comment by xamanu** [comment] 2016-08-01 08:55
This was intended to show only the first item's image in the redesign process. So, I can't see here the issue. Please explain further or close. Thanks!

**Comment by cgiovando** [comment] 2016-08-01 09:17
OK, sorry, I don't remember that discussion. Can you remind me of the reasoning behind that choice? To me it seems an inconsistent design to have one item with the background and two without.

**Comment by xamanu** [comment] 2016-08-01 09:29
First, to let you know, I don't consider the redesign as something static that we should not touch anymore! I think we should always be able to step forward. And if there is something we could do better, we can just do it.

We wanted to give the first news item a more prominent position and a picture for all news items would cause a heavy accumulation within a pretty clean and bright design. I'm also with you that it doesn't look perfect. Maybe we want to show two articles vertically separated to fit the three column layout of the website and show the pictures above them, as it is on the general news listing page...

**Comment by cgiovando** [comment] 2016-08-01 10:30
I see. OK, I'll leave it open for discussion then. At the moment the three news items seem a little bit hidden down the page anyway, so I'm not sure if having a background for the top one only really makes a difference in drawing attention. I would definitely be interested to test different layout options with news items moved up higher in the page. Thanks @xamanu

**Comment by smit1678** [comment] 2018-07-17 13:04
Issue related to old version. Closing.

**Closed by smit1678** 2018-07-17 13:04 UTC
