### ISSUE TITLE
Error on user page: Notice: Undefined index: title in field_extra_fields_get_display

### ISSUE THREAD

**Issue by harry-wood** [hotosm/hotosm-website#35] opened 2015-01-14 19:14 UTC
What's wrong on this page? http://hot.openstreetmap.org/user/52

Currently showing the error "Notice: Undefined index: title in field_extra_fields_get_display() (line 682 of /var/www/modules/field/field.module)."  in a red box at the top

**Comment by ifrik** [comment] 2015-01-14 21:49
I'm looking into it.

**Comment by xamanu** [comment] 2015-04-30 23:31
I can't reproduce this (anymore). So closing, here...

**Closed by xamanu** 2015-04-30 23:31 UTC
