### ISSUE TITLE
Link not working in donate page

### ISSUE THREAD

**Issue by bismitaguha** [hotosm/hotosm-website#473] opened 2019-03-20 05:40 UTC
Few links are not working on donate page due to wrong 'href' and are redirecting to error page.

![Screenshot from 2019-03-20 11-09-24](https://user-images.githubusercontent.com/43119923/54661557-bc22ef00-4b00-11e9-94fe-03d3dec10c4c.jpg)

**Comment by bismitaguha** [comment] 2019-03-20 05:41
@ramyaragupathy I am taking up this issue.

**Comment by ramyaragupathy** [comment] 2019-03-20 06:05
Can you mention specifically what's not working here @codefab99

**Comment by bismitaguha** [comment] 2019-03-20 06:06
@ramyaragupathy the paper form link

**Comment by ramyaragupathy** [comment] 2019-03-20 06:13
Duplicate of https://github.com/hotosm/hotosm-website/issues/460

**Closed as completed by ramyaragupathy** 2019-03-20 06:13 UTC
