### ISSUE TITLE
Extra black area coming on hotosm.org/impact-areas/disaster-risk-reduction/ page

### ISSUE THREAD

**Issue by ananya** [hotosm/hotosm-website#466] opened 2019-03-19 18:07 UTC
There is an extra black doted area coming in background on page hotosm.org/impact-areas/disaster-risk-reduction/
![Screenshot from 2019-03-19 23-34-18](https://user-images.githubusercontent.com/33188930/54630389-b77a1e80-4a9f-11e9-95eb-d8ed1bf26f3b.png)

This could be changed to have a white background instead.

If it is really a bug then I would like to work on this.

**Comment by ramyaragupathy** [comment] 2019-03-20 03:24
This is a design element and not a bug- closing here @ananya

**Closed as completed by ramyaragupathy** 2019-03-20 03:24 UTC

**Comment by ananya** [comment] 2019-03-20 07:58
Actually this caused because some of the <div> were not closed. And moreover the file had some extra code wrongly placed
