### ISSUE TITLE
Projects being loaded takes much time.

### ISSUE THREAD

**Issue by richa031** [hotosm/hotosm-website#509] opened 2019-03-25 13:25 UTC
It takes very long time to load the projects on the website. As a user people think there are no projects and move to other links.

![Screenshot from 2019-03-26 00-22-24](https://user-images.githubusercontent.com/32764563/54923012-5931bd80-4f2f-11e9-91b1-d802b84d3a3f.png)

We can check if something can be done here.

**Comment by ramyaragupathy** [comment] 2019-03-25 13:27
Hi @richa031 - Thanks for taking the time to dig into the tool. Since the issue is related to the Tasking manager recommend you to continue discussion in [hotosm/tasking-manager](https://github.com/hotosm/tasking-manager/issues) repo.

Closing here!

**Closed as completed by ramyaragupathy** 2019-03-25 13:27 UTC

**Comment by richa031** [comment] 2019-03-25 17:31
@ramyaragupathy  I'm extremely sorry for the inconvenience caused.
