### ISSUE TITLE
Lead visitors to become contributers

### ISSUE THREAD

**Issue by malenki** [hotosm/hotosm-website#41] opened 2015-03-24 19:24 UTC
[Feature request]

When a visitor interested in helping HOT by enhancing OSM data he has (imho) a hard time finding the right place. Right now he has to discover the "get involved" link (which shouldn't be too hard) – but the link pointing to the task manager is in the middle of the following page "hidden" in a big text block.

**Comment by ifrik** [comment] 2015-03-25 09:45
Good point, there is lot of information on that page, but the structure probably doesn't fit anymore. Do you have ideas on how to re-do it?

**Comment by malenki** [comment] 2015-03-25 18:48
ifrik schrieb
am Wed, 25 Mar 2015 02:45:17 -0700:

> Good point, there is lot of information on that page, but the
> structure probably doesn't fit anymore. Do you have ideas on how to
> re-do it?


Maybe a structure similar to this:

If you want to:

==  enhance maps ==

do
a) learnosm<link>

if you know a), do
b) look at the Taskmanager wiki <link> how to contribute to HOT

if you know b), do 
c) select a mapping task at Taskmanager<link>

== talk ==
HOT Mailing lists <link>
IRC <link>

== develop ==
<stuff which is now at the website>

== join HOT ==
<stuff which is now at the website>

**Comment by xamanu** [comment] 2015-04-30 23:34
Clearly related to a new design (#23) and should be taken into consideration

**Comment by xamanu** [comment] 2015-05-01 01:10
I would actually consider this as a duplicate of: #21 
Therefore closing here.

**Closed by xamanu** 2015-05-01 01:10 UTC
