### ISSUE TITLE
Migration plan

### ISSUE THREAD

**Issue by smit1678** [hotosm/hotosm-website#134] opened 2018-01-22 16:51 UTC
Starting a thread about migrating old content. 

### Currently
We have the following content types on the Drupal site:
- Job
- Partner
- Project
- Showcase
- Static page
- Update
- Video
- Working Group

### Considerations 

@brendangatens and I briefly discussed that the best plan of action is to look to move these into generic pages on the new website. In the near term, we won't necessarily create a specific style for old blog posts or projects but look to incorporate into the new styles or just a generic layout that works. Over time we can revisit some of the pages to fix things that look broken. We'll need to come up with a plan for images. 

Of the old content, some of it should just be completely rewritten. 

If we need to think about redirects or restructuring URLs of old content to make sure it makes it to new content, then we can look at a plugin like https://github.com/nquinlan/jekyll-pageless-redirects. 

Any other considerations? 

**Next action:** outline backlog for getting started extracting old content and organizing it for the new site.

**Comment by dakotabenjamin** [comment] 2018-02-27 14:50
Working on the migration, of content using a slightly custom [jekyll-import](https://github.com/dakotabenjamin/jekyll-import/tree/filename-length) which gets us 50% of the way. The content is there, but it still needs to be laid out properly, which means either editing the importer tool to query/parse the metadata, or adjusting how the layout parses the generated metadata, or some of both. 

For example the migrated content has an "excerpt" tag which is analogous to the "Summary Text" tag. 

There are some things that are not migrated at all. Associated countries and projects, images, author. These can be queried in the import tool and added. 

And there is a tag that isn't used in the new layout: categories. I don't know what to do with these. 

Lastly images are not imported. That is a future dakota problem.

**Comment by dakotabenjamin** [comment] 2018-02-27 14:58
Process for importing using a local db: 
add these gems to Gemfile: 
```
   gem "jekyll-import", :git => 'https://github.com/dakotabenjamin/jekyll-import.git', :branch => 'filename-length'
   gem "sequel"
   gem "mysql2"
   gem "pg"
```
run `bundle install`

`bundle exec jekyll import drupal7 --dbname drupal-site --user root --types update --engine mysql --password [redacted] --trace`

AFAIK once the import is complete we can remove the gems.

**Comment by brendangatens** [comment] 2018-02-28 09:50
Hey @dakotabenjamin, I'm getting an error caused by `filename-length` (the branch listed above) not being found. Is there another branch that this should be using?

Also, categories are present by default in Jekyll; we aren't using them, however. We may find a use for them in the future, but you can ignore categories as far as the import goes.

**Comment by dakotabenjamin** [comment] 2018-03-01 16:17
Sorry, I switched to the `add-author` branch. 

What about the layout tag? I was getting errors and have to remove that because it seems we are using a different method for assigning page layouts

EDIT: For the gemfile you can also specify `:path => ` for a local gem resource.

**Comment by dakotabenjamin** [comment] 2018-03-01 20:44
I'm nearly done with the Updates/Posts import: https://dakotabenjamin.github.io/hotosm-website/updates/

Current issues: 
- Names / Authors: There are some names that got imported that aren't regular- like "RebeccaFirth", "russell deffner", or "Douglas" so they won't necessarily translate to someone in "/people"
- The "/updates" page seems to repeat the contents of the page three times
- I don't have any information on countries from the drupal db, or I am unable to find it. Was this information being tracked before? 
- Images and links are not working yet. I could use advise here.

**Comment by brendangatens** [comment] 2018-03-02 08:56
I was only working with just a few sample posts when styling and creating pagination, so I looped through the posts three times in order to display more posts on the page. I'll get rid of that loop.

I don't think countries were tracked or tagged in previous posts. There will be some manual work involved here.

Images and links probably aren't working because their paths are relative to the root and not to `/hotosm-website`. Nate and I discussed this but we were unable to come up with a perfect solution considering the root is where we'll want these paths to be once finished and live. I assume images and links work when viewing locally?

**Comment by smit1678** [comment] 2018-03-05 09:53
> Images and links probably aren't working because their paths are relative to the root and not to /hotosm-website. Nate and I discussed this but we were unable to come up with a perfect solution considering the root is where we'll want these paths to be once finished and live. I assume images and links work when viewing locally?

Now that we're at http://www-dev.hotosm.org/, all links and paths should be working correctly

**Comment by brendangatens** [comment] 2018-03-05 10:06
@dakotabenjamin and I chatted about just doing a project-wide _find and replace_ for any of those recurring errors (like the lack of space in _RebeccaFirth_.

I haven't yet migrated the posts in to my working branch. I got an error attempting the migration last week so I figured I'd wait until the migration work was finished. It hasn't held me up at all.

**Comment by smit1678** [comment] 2018-03-05 11:18
> I don't have any information on countries from the drupal db, or I am unable to find it. Was this information being tracked before?

Yeah I think the only place where countries is captured on the Drupal site is the Voting Members: https://www.hotosm.org/users/adityo_dwijananto

**Comment by dakotabenjamin** [comment] 2018-03-05 16:37
Possible ways to handle countries:
- don't add it to the migration 
- scrape locations from the body content (may grab irrelevant information)
- go through it by hand

**Comment by smit1678** [comment] 2018-03-06 12:28
thanks @dakotabenjamin, agreed. How about we leave this out of the migration and create the country pages by hand (or through a short script)? Since we want to have pages for all countries, whether there is a project or person there or not, we should pregenerate markdown files with metadata.

**Comment by dakotabenjamin** [comment] 2018-03-06 14:39
So I'm more or less done with migrating the updates content. I just have to fix the author names, but I think I might wait until the users/persons pages are more filled out. 

Now I'm going to work on the  the rest of the content. I have to 
- Get feedback from @smit1678 and @brendangatens 
- determine if jekyll-import is still the right tool for the other stuff (it was very good for blog posts, not so sure about the rest)
- determine which parts need migration and which can be updated easily by hand


EDIT: See #149

**Comment by dakotabenjamin** [comment] 2018-04-12 16:02
@smit1678 can we close this or are there more migrations I've missed?

**Comment by smit1678** [comment] 2018-04-12 16:05
👍 yes, we just need to do some brief manual migration of some of the latest posts when we're ready

**Closed as completed** 2018-04-12 19:45 UTC
